# print("Hello World")
# print('Hello World')
# print('a')
# print("a")
# print(-10)
# print(10)
# print(20+10)
# print(20-10)
# print(20*10)
# print(20/10)
# print(20%3)
# print('20을 3으로 나눈 나머지=',20%3)
# print(10*9)
# print('10'*9)
# print('India\'s best')
# print('Indian\n -food')
# print('Indian\t -food')
# print('$5,000')
# print('★세프 추천※')

mylist = ['apple','banana','cherry']
print(len(mylist))
